default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_dev
  password: aqwe123
  pool: 5

development:
  <<: *default
  database: someblog_development

test:
  <<: *default
  database: someblog_test

production:
  <<: *default
  database: someblog_production
  username: someblog
  password: <%= ENV['SOMEBLOG_DATABASE_PASSWORD'] %>
